[project]
name = 'Precision-Agriculture-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.crop-prediction]
path = 'contracts/crop-prediction.clar'
clarity_version = 2
epoch = 2.5

[contracts.farm-management]
path = 'contracts/farm-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-optimization]
path = 'contracts/resource-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.sensor-data]
path = 'contracts/sensor-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
